### ISSUE TITLE
feature(LitHtml): we need to have ability to develop components inside YML file.

### ISSUE THREAD

**Issue by Stradivario** [rxdi/graphqj#12]
For example we can have the following configuration

```yml
$views:
  home:
    query: findUser
    props: User
    output: UserPayload
    html: |
      <bla-component></bla-component>
      {userId} {name} {email} {phone} {createdAt}
      A rich framework for building applications and services with GraphQL and Apollo inspired by Angular
```
