### ISSUE TITLE
feature(Subscription): provide options to define Mutation and Subscriptions

### ISSUE THREAD

**Issue by Stradivario** [rxdi/graphqj#4]
By default this library was not intended to go to production but it become really awesome experience to develop and everything is working really smoothly and without problems.

Type of change: Missing feature request

# Description
Currently when defining resolvers we don't have option to select what type Query we are defining

# Example

```yml
$mode: advanced
$resolvers:
  findUser:
    type: User
    args:
      payload: UserPayload
    resolve: 💉./findUser.ts
```

This confuguration will create Query Graphql type but how to specify Mutation ?!? or Subscription ?!?

```yml
$mode: advanced
$resolvers:
  findUser:
    type: User
    method: 'Query' | 'Mutation' | 'Subscription'
    args:
      payload: UserPayload
    resolve: 💉./findUser.ts
```

This is just a proposal implementation nad maybe it will change
